### ISSUE TITLE
M5 Level Bar

### ISSUE THREAD

**Issue by cpyarger** [ropg/M5ez#11]
Please add class m5 Level bar

- Works like the current progress bar implementation. 
- allows up to 8 level bars to be displayed per screen. 
- optional shows a changing value below or above the level bar, as well as an assignable label. 
- optional selected state (just changes color of the selected level bar to indicate it is selected.)

**Comment by ropg** [comment]
I'm still in awe of some of the interface mockups I've seen. And still thinking how to make that possible. I think what we need is a way to have JPG buttons (with optional text printed on top), and a way to use transparent images as parts of sliders etc. Closing this for now because it's not really an issue with the code. But rest assured my mind is turning...
