### ISSUE TITLE
graphics

### ISSUE THREAD

**Issue by skysingh** [ropg/M5ez#16]
Thanks for a nice library and great documentation. Question - to draw rectangles etc do I need to use M5.lcd. routines ? So I must include M5stack.h ? Also in your examples you never call M5.update(). Is this not necessary ?

**Comment by ropg** [comment]
> to draw rectangles etc do I need to use M5.lcd. routines ? 

Yes. You draw on the canvas using `m5.lcd.` functions, preferably using `ez.canvas.top()` and `ez.canvas.height()` to make sure you do not draw in areas that are used by header or buttons.

> So I must include M5stack.h ?

correct

> Also in your examples you never call M5.update(). Is this not necessary ?

Indeed, because `ez.yield()` calls `m5.update()`. `ez.yield()` is called from any place where M5ez waits for user input. And you can call it yourself if for some reason you need to do something for a longer time, which would not only do `m5.update()` but also update the wifi signal icon and the clock in the header.
