### ISSUE TITLE
Enhancement Requests

### ISSUE THREAD

**Issue by TotallyInformation** [ropg/M5ez#3]
Sorry to drop this in now, I know you are preoccupied and I don't want you to even think about this until things are more normal again. I just didn't want to lose the thoughts. Hope they are helpful.

----

Still liking this library which seems well in advance of any of the others 🥇 

A few things I find myself wishing for & would be interested in your feedback on:

1. The most critical issue is that, when you are waiting for menu/textbox responses, you stop the main loop. This means that nothing else can happen. My MQTT output stops and the broker thinks that the unit is offline.

    This really limits the usefulness of the library unfortunately. I'm not a strong enough C++ programmer to know if there is any way to get round this issue?

    For now, I'm partially getting round this by the use of FreeRTOS background tasks.

2. Being able to scroll the display when print/println reaches the end of the canvas.

    Looking at [your code](https://github.com/ropg/M5ez/blob/master/src/M5ez.h#L124) it seems as though you have something that isn't quite working yet?

3. Having a flag that indicates when print/println is *about* to reach the end of the canvas - so that we can clear the canvas manually if we don't want scrolling.

    As a minimum, perhaps you could expose `_print_x` and `_print_y` so that it was easier to do our own calculations if needed?

4. In the WiFi menu, it would be much nicer to be able to go up from the 1st menu entry to the last. It is a bit of a pain if you've gone into the menu and then want to exit immediately.

5. In the WiFi menu and probably in the sysinfo app as well, it would be really nice to show the device's IP address and maybe MAC address. Would make things a lot easier when working with DHCP.

**Comment by ropg** [comment]
1. I have been thinking about something like `ez.loopFuntion(yourFunction)` that would insert your own function in all the M5ez loops. yourFunction could maybe return either `CARRY_ON`, `REDRAW` (if it has been putting stuff on the screen) or `EXIT` to tell M5ez what to do. The problem is that that quickly gets complicated if you decide to use M5ez functions while interrupting the main flow, because what if they get interrupted in turn...?  Requires a bit more thinking on my part. And yes: for some things having a separate FreeRTOS task is the way to go. Possibly using some variable/semaphore, whatnot to talk back to the side that runs the M5ez. Another crazy thought is to allow the interrupting event to start a whole new instance of M5ez... I'll think about how to do this cleanly and in a way that is easy to grasp. Some of this may have to come after some code cleanup to simplify things that have become needlessly complicated in there...

2. Scroll doesn't work because the display driver's `readRect` function returns white pixels. See http://forum.m5stack.com/topic/277/scrolling-m5-lcd-readrect/1

3. I'll think of exposing _print_x and _print_y. I generally hate doing that, might make `getPrintX()` and `getPrintY()` methods instead.

4. I'll do that or add exit as a long press function on the up button. I was thinking of making that an M5ez standard throughout. Also gets people in the mindset that you can have long press functions.

5. Once you're connected, select the menu item that says which network you're connected to.


Thank you for these suggestions. Once I finish the time library, I'll get to it.

**Comment by TotallyInformation** [comment]
Hi, thanks for the response. I am slowly working through how to really use the M5stack. I'm not really a low-level person so it will take me a while - I thought that the ESP8266 and Arduino's were complex! Fun though.

1. Thanks for thinking about this. While not an expert, your first idea doesn't sound that usable I'm afraid. I guess I was hoping that there was some way your loops could give some time back to the main loop so that they weren't blocking. For example, if you see the [example code for the MQTT library](https://github.com/256dpi/arduino-mqtt/blob/master/examples/ESP32DevelopmentBoard/ESP32DevelopmentBoard.ino#L57) I'm using, you will see that it has a "loop" function so that the loop is driving things and not a separate while loop. That way the loop can carry on working as long as the loop function doesn't block things for too long. I think this is a common pattern?

    Certainly, I'll be investigating more about background tasks and semaphores. One interesting thought has been around being able to monitor the time since the last button press and so put the device to sleep. I think this could be done fairly easily but would require a global variable to track and some amendments to your code so that the variable is updated whenever a button is pressed (in your menu/dialog boxes as well as manually). The actual monitor/poweroff could happen in a background task.

2. Got that. Annoying but such is life :)

3. get fns would be absolutely fine.

4. Great! Thanks. I've also implemented exit as long presses under both buttons A and C in my own main menu. Long press on B actually power's off - I've set B to be the wakeup button as well for consistency.

5. Urm! Some some reason that didn't occur to me 😊 Well, I've amended your sysinfo ino for my own use anyway as I'm lazy and want one less button press. I also amended it so that the button presses rotate screens - of course. Also slightly refactored in case I need to add another screen.

I will push the code up to GitHub when it (and I!) calms down a little.

I need to refactor my own information screens next. Since I am updating them from received MQTT data, I get quite a few update flashes so I need to change from print/println with automatic line feeds to manual placements. Effectively, I need to create a grid layout so that I can update just individual cells.

All-in-all though, I couldn't have come so far so quickly without your library so many thanks yet again.

**Comment by malbrook** [comment]
Hi
I have a package working on M5Stack using M5ez for menus with a second task ( a modbus communications task), running on the other core of the processor. This second task runs by independently from the normal main loop  so does not suffer any interference from the menus.  Might be the way to go.

**Comment by ropg** [comment]
1. M5ez 2.0.0 is out. It allows for you to add a task to its loop. Use [`ez.addEvent`](https://github.com/ropg/M5ez#your-own-events) to add your function. This function needs to take no arguments and return a uint16_t that holds in how many milliseconds it should be executed again. So returning 1000 would create a function that runs once a second. Simply add a wrapper function if the function you'd like to run does not return a number like that.

2. ez.canvas now inherits from Print object _and_ scrolls (M5ez creates its own scroll buffer...)

3. ez.canvas.x() and ez.canvas.y()

4. Throughout the M5ez menus, a long press on the left button takes you a level up.

**Comment by bmueller78** [comment]
Question: is it possible to leave a submenu without user intervention? I would like to have a timeout function e.g. with ez.addEvent, which causes the menu to close after a certain time or to go one level higher.
