### ISSUE TITLE
Crash after repeated screen updates

### ISSUE THREAD

**Issue by andyrbarrow** [ropg/M5ez#38]
My application does a repeated update of the canvas from incoming data. Right now, it's three lines of data that are updated every second.

In my first iteration, I did an ez.canvas.clear() before doing any update to the canvas. That seemed to work fine, except that the screen flickered too much. So, I started writing a background-color rectangle over just the line to be updated. 

Flickering is reduced, but after about a minute the M5Stack crashes and reboots.

I'm trying to understand what ez.canvas.clear() does that might be different from just writing a rectangle at a specific place on the screen. From the code, it appears that it simply writes a new background-color rectangle to the screen that is the size of the canvas.

**Comment by ropg** [comment]
This happens because my `ez.canvas.print` code retains everything that is printed in memory so that it can scroll the screen. The problem occurs when things are repeatedly printed and then deleted by user code.

Version 2.1.0, releasing now, fixes the problem by turning scroll off by default and not storing to memory when scroll is off.
