### ISSUE TITLE
#include "images.h"

### ISSUE THREAD

**Issue by twegithub** [ropg/M5ez#44]
I am new to all this and barely know what I am doing.  Your work with M5ez is amazing and incredibly useful.  My IDE compilation hangs up due to the lack of library on the following line:
#include "images.h"

I cannot find where to add this library.  

Can you please help?

**Comment by ropg** [comment]
The only place I can find where any of my code includes an `images.h` is in the m5ez-demo code. That comes in its own directory, which includes that file. 

The easiest way to try the demo app is to select it from the File / Examples / M5ez menu in the Arduino GUI. Otherwise please tell me exactly what you are doing to get this error...

**Comment by twegithub** [comment]
Rop,
That worked!  I reloaded the M5ez -demo code and it picked up the images.h
library.  All good.

You have written a valuable menu system for the M5STACK.  It is very useful
and I thank you so much for helping me.  Great contribution!

Best wishes.
Tom

*Tom Evernham  W9GBA*
*Spruce Creek Fly-In, Port Orange, FL*
  (summer - Sylvan Heights Mountain Community, Brevard, NC)
VoIP: 386.304.8233    Cell:  386.679.9702
tomevernham@gmail.com
[image: Picture]

**Comment by twegithub** [comment]
Rop,
That worked!  I reloaded the M5ez -demo code and it picked up the images.h library.  All good.

You have written a valuable menu system for the M5STACK.  It is very useful and I thank you so much for helping me.  Great contribution!

Best wishes.
Tom

**Comment by ropg** [comment]
I'm glad you enjoy using M5ez...

Have fun,

Rop
