### ISSUE TITLE
WiFi did not connect with password

### ISSUE THREAD

**Issue by technerdchris** [ropg/M5ez#60]
I tried joining the WiFi of Netgear R7000 and m5ez said it couldn't connect, wrong password, or something. The password was correct and I verified by logging into the router. The router had the options for WPA AES or TKIP and AES was selected. Is the m5ez (or ESP32) only work with TKIP? 

I was able to connect with WPS button, which I had to research where the button was on my router... 😄

**Comment by ropg** [comment]
The ESP32 has problems connecting with some Access Points, and it hasn't always been clear to me what the problem was. Sometimes indeed fumbling with the encryption options helped, other times switching to a different AP was the answer, there were even some passwords that did not work, possibly because some special characters were not liked by the ESP32? Also always make sure you use the latest Espressif software on your ESP32.

Glad it worked for you, and yes, it can be tricky. None of the problems I have seen so far had anything to do with M5ez, but I'm not ruling out bugs on my part either... Please reopen if there's a setup that works on the M5 but not with M5ez.
