### ISSUE TITLE
Using SD card for images

### ISSUE THREAD

**Issue by malbrook** [ropg/M5ez#7]
Is there any way to remove the image arrays and instead use images on an SD card (or SPIFFS), I would like to make use of the image menus but due to the complexity of application I have run out of flash using the normal 2 OTA partitions plus SPIFFS.

**Comment by ropg** [comment]
It was on my list of additions: to add the possibility to supply a filename instead of a pointer to the array for the image. SPIFFS and SD card both get mounted in the same file tree (/sd and /spiffs), so they would both work.

In the mean time: do you need OTA? Otherwise you could go to Tools / Partition Scheme / No OTA and get twice the space. Or make the SPIFFS smaller (also an option there)... Did you see [this uploader for SPIFFS](https://github.com/me-no-dev/arduino-esp32fs-plugin)?

(I'll keep the issue open so I add the file path option)

**Comment by malbrook** [comment]
Fraid not, the application includes OTA from external server via WiFi, AsynWebServer to display various web pages via SoftAP, uses the second core to run a background task for communications as well as M5ez for menus. It currently compiles to 1197678 bytes so adding any more images takes it over the limit.  Only real option is to drop the image menu and use simple text but doesn't give the same feel to the application.

I use the uploader to update my SPIFFS which contains various html pages, jquery, and css files which is running at 358kBytes, leaves almost a Megabyte free so might be worth droping the size of SPIFFS and increasing the two OTA partitions to get more room.

From an efficiency point of view moving the images to the SPIFFS folder is a more efficient use of the space otherwise having two OTA partitions means I need twice the space if the images are in the code than if they are held once in SPIFFS.

How big a job is it to make this change, I will dig into the library to see what I can do.

**Comment by ropg** [comment]
In version 1.3.0 - just released - `addItem` now supports

```
images.addItem(SPIFFS, "/rose.jpg", "Rose");
```

See the "ImagesSPIFFSorSD" example...
